// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LittleHairSalon.Models;

#nullable disable

namespace LittleHairSalon.Migrations
{
    [DbContext(typeof(LittleHairSalonContext))]
    [Migration("20260328104706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LittleHairSalon.Models.ChiTietDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaHang")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A1141442DD17");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietDon", (string)null);
                });

            modelBuilder.Entity("LittleHairSalon.Models.DonHang", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PTThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Mới đặt");

                    b.HasKey("MaDon")
                        .HasName("PK__DonHang__3D89F568A1A9CF9C");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("LittleHairSalon.Models.Hang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHang")
                        .HasName("PK__Hang__19C0DB1D8F92390E");

                    b.HasIndex("MaLoai");

                    b.ToTable("Hang", (string)null);
                });

            modelBuilder.Entity("LittleHairSalon.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("LittleHairSalon.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__Loai__730A57597318615E");

                    b.ToTable("Loai", (string)null);
                });

            modelBuilder.Entity("LittleHairSalon.Models.ChiTietDon", b =>
                {
                    b.HasOne("LittleHairSalon.Models.DonHang", "MaDonNavigation")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("MaDon")
                        .HasConstraintName("FK__ChiTietDo__MaDon__52593CB8");

                    b.HasOne("LittleHairSalon.Models.Hang", "MaHangNavigation")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("MaHang")
                        .HasConstraintName("FK__ChiTietDo__MaHan__534D60F1");

                    b.Navigation("MaDonNavigation");

                    b.Navigation("MaHangNavigation");
                });

            modelBuilder.Entity("LittleHairSalon.Models.Hang", b =>
                {
                    b.HasOne("LittleHairSalon.Models.Loai", "MaLoaiNavigation")
                        .WithMany("Hangs")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__Hang__MaLoai__4BAC3F29");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("LittleHairSalon.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDons");
                });

            modelBuilder.Entity("LittleHairSalon.Models.Hang", b =>
                {
                    b.Navigation("ChiTietDons");
                });

            modelBuilder.Entity("LittleHairSalon.Models.Loai", b =>
                {
                    b.Navigation("Hangs");
                });
#pragma warning restore 612, 618
        }
    }
}
